name: task_manager_by_abdullah
description: Task Manager app with SQLite, local notifications, export, MVVM + Provider.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  csv: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.13.1
  timezone: ^0.9.3
  share_plus: ^7.2.2
  path: ^1.9.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3+1
  lints: ^3.0.0

flutter:
  uses-material-design: true

